# Generated by Django 2.1.15 on 2020-09-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200928_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('is_accepted', models.BooleanField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_accepted', models.DateTimeField(null=True)),
                ('to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile', to_field='user_id')),
            ],
        ),
    ]
