# Generated by Django 2.1.15 on 2020-09-28 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='invitation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
