# Generated by Django 2.1.15 on 2020-09-28 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_friend_invitation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('post', 'post'), ('friend', 'friend')], max_length=100)),
                ('uid', models.CharField(max_length=255)),
                ('is_seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile', to_field='user_id')),
            ],
        ),
    ]
