# Generated by Django 2.1.15 on 2020-09-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
